language: java
cache:
jdk:
- oraclejdk8
script:
- mvn clean package

sudo: required
services:
- docker
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package
- docker build -t docker.io/jverhulst/movieinfoservice:0.0.1 .
- docker push docker.io/jverhulst/movieinfoservice:0.0.1
